FROM dailygrommet/php-base
LABEL description="The Grommet PHP CLI Base"
LABEL maintainer="todd@thegrommet.com"

COPY docker-php-entrypoint /usr/local/bin/docker-php-entrypoint
RUN chmod +x /usr/local/bin/docker-php-entrypoint
